// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ2rOLMVRntEeNLpPHrXK5_m715aUIpwE',
    appId: '1:561927875667:web:e45458db9d04bbc3f06aa6',
    messagingSenderId: '561927875667',
    projectId: 'organization-app-a1e71',
    authDomain: 'organization-app-a1e71.firebaseapp.com',
    databaseURL: 'https://organization-app-a1e71-default-rtdb.firebaseio.com',
    storageBucket: 'organization-app-a1e71.appspot.com',
    measurementId: 'G-87P069E7YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJUcW6_8u-HNboJyIjEW1E2NYIQt9W2-k',
    appId: '1:561927875667:android:0506938aa74ea914f06aa6',
    messagingSenderId: '561927875667',
    projectId: 'organization-app-a1e71',
    databaseURL: 'https://organization-app-a1e71-default-rtdb.firebaseio.com',
    storageBucket: 'organization-app-a1e71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-MMwuOm6isq7DRD1xr6SFPfK7RsUF6M',
    appId: '1:561927875667:ios:7f716d6ca1bae8baf06aa6',
    messagingSenderId: '561927875667',
    projectId: 'organization-app-a1e71',
    databaseURL: 'https://organization-app-a1e71-default-rtdb.firebaseio.com',
    storageBucket: 'organization-app-a1e71.appspot.com',
    iosClientId: '561927875667-090r2usluh15lfh5h1u362rba4roajtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.orgmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV-MMwuOm6isq7DRD1xr6SFPfK7RsUF6M',
    appId: '1:561927875667:ios:7f716d6ca1bae8baf06aa6',
    messagingSenderId: '561927875667',
    projectId: 'organization-app-a1e71',
    databaseURL: 'https://organization-app-a1e71-default-rtdb.firebaseio.com',
    storageBucket: 'organization-app-a1e71.appspot.com',
    iosClientId: '561927875667-090r2usluh15lfh5h1u362rba4roajtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.orgmeApp',
  );
}
